version: '3.4'

services:
  isa.application.api:
    image: ${DOCKER_REGISTRY-}isabackv1
    container_name: isa.beckend.apiv1
    build:
      context: .
      dockerfile: ISA.Application.API/Dockerfile
    ports:
      - 5000:5000
      - 5001:5001
      - 7109:7109
      - 5121:5121