version: '3.4'

services:
  isa.application.api:
    image: ${DOCKER_REGISTRY-}isaapplicationapi
    container_name: isa.api
    build:
      context: .
      dockerfile: ISA.Application.API/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
      - "7109:7109"
      - "5121:5121"

  isa.database:
    image: postgres:latest  
    container_name: isa.database
    environment:
      - POSTGRES_DB=ISA2023
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=super
    ports:
      - 5432:5432